### ISSUE TITLE
docker-compose run -ti [..]

### ISSUE THREAD

**Issue by Op3rat0r** [Riodigital-de/passbolt-docker-compose#3]
Hi,
there are no options "-ti" in docker-compose.
```
docker-compose version 1.11.2, build dfed245
Docker version 17.03.1-ce, build c6d412e
```

Available options at docker-compose are:

```
Run a one-off command on a service.
For example:
    $ docker-compose run web python manage.py shell

By default, linked services will be started, unless they are already
running. If you do not want to start linked services, use
`docker-compose run --no-deps SERVICE COMMAND [ARGS...]`.

Usage: run [options] [-p PORT...] [-e KEY=VAL...] SERVICE [COMMAND] [ARGS...]

Options:
    -d                    Detached mode: Run container in the background, print
                          new container name.
    --name NAME           Assign a name to the container
    --entrypoint CMD      Override the entrypoint of the image.
    -e KEY=VAL            Set an environment variable (can be used multiple times)
    -u, --user=""         Run as specified username or uid
    --no-deps             Don't start linked services.
    --rm                  Remove container after run. Ignored in detached mode.
    -p, --publish=[]      Publish a container's port(s) to the host
    --service-ports       Run command with the service's ports enabled and mapped
                          to the host.
    -T                    Disable pseudo-tty allocation. By default `docker-compose run`
                          allocates a TTY.
    -w, --workdir=""      Working directory inside the container
```
Am I doing something wrong?
In addition, the service should not run on the standardPorts. Is it sufficient to specify other ports in the command?

Regards,
Daniel

**Comment by DerDummePunkt** [comment]
Oh, nice catch with the -ti, apparently the default behaviour of docker-compose changed with some update, since docker-compose now allocates a TTY per default, just remove the -ti option from the statement, i'll update the readme.

Regarding the second question: What service are you talking about? The proxy, the db or the app?
Why shouldn't they run on the standard ports?

I'm guessing what you want to do is change the host port binding for ports 80 and 443 for the proxy container, am I right?
That shouldn't be to hard, just change the first number, before the colon, to whatever u want to bind the ports to, so, if you want to map port 80 to 8081 and 443 to 4567, the command to start the proxy container the first time for the letsencrypt certbot should be something like
`docker-compose run -p 8081:80 -p 4567:443 proxy bash`

Note that you will probably also have to change these bindings in docker-compose.yml (or your override, if you use any)

**Comment by Op3rat0r** [comment]
I've also omitted the option (-ti) and got a bash. But I was not aware if it worked so.

I do not know yet so well with Docker from. I already have another Docker Compose running on the server. There is also an Nginx on port 80/443. So I wanted to run this Nginx-"Proxy" on a different port.

No I tried to run the proxy like
`docker-compose run -p 8081:80 -p 4567:443 proxy bash`

But when I try a dry-run.sh
```
Failed authorization procedure. pass.domain.tld (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 295d6810ac05b18bf2b927b3b55c029e86cdc79633.acme.invalid from xxx.xxx.xxx.xxx:443. Received 2 certificate(s), first certificate had names "autoconfig.domain.tld, autodiscover.domain.tld, mail.domain.tld"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: pass.domain.tld
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   295d6810ac05b18bf2be4b4fb2d10927b3b55c029e86cdc79633.acme.invalid
   from xxx.xxx.xxx.xxx:443. Received 2 certificate(s), first certificate
   had names "autoconfig.domain.tld, autodiscover.domain.tld,
   mail.domain.tld"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

As you can see at the output, something already runs on the port when I try to start the script. For Letsencrypt, something needs to be changed? Ich changed the Ports in the docker-compose.yml like in the `docker-compose run` command.

**Comment by DerDummePunkt** [comment]
Yeah, that won't work, afaik certbot only works on 443, since tls-sni-01 only works on 443.

My suggestion would be to setup a third nginx as a reverse proxy (something like [https://hub.docker.com/r/jwilder/nginx-proxy/](https://hub.docker.com/r/jwilder/nginx-proxy/) ), only bind the host ports to the 3rd nginx, let that one handle redirects and don't bind any ports on the passbolt docker-compose and your other compose stack.

I'm going to close this issue, since it clearly isn't an issue with this repo
